### ISSUE TITLE
Code reformat stopped working in Rider 2021.2

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#133]
STR:
1. Open Rider 2021.2 EAP 3
2. Open a project with specflow enabled
3. Try to reformat a feature file

ACTUAL:
Formatting doesn't work
[Log1](https://youtrack.jetbrains.com/issue/DEXP-591543)
[Log2](https://youtrack.jetbrains.com/issue/DEXP-591544)

**Comment by tkapustina** [comment]
Rider 2021.2 EAP 3 will be released this week or I can send the build in advance.

**Comment by tkapustina** [comment]
I guess it's related [https://youtrack.jetbrains.com/issue/DEXP-591903](https://youtrack.jetbrains.com/issue/DEXP-591903).
```
ClassName = System.ArgumentNullException
HResult = E_POINTER=COR_E_NULLREFERENCE=80004003
Source = System
ParamName = input

StackTraceString = “
at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
at TechTalk.SpecFlow.Tracing.CodeFormattingExtensions.RemoveQuotationCharacters(String text) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Utils\Steps\CodeFormattingExtensions.cs:line 210
at TechTalk.SpecFlow.Tracing.CodeFormattingExtensions.ToIdentifierPart(String text) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Utils\Steps\CodeFormattingExtensions.cs:line 46
at TechTalk.SpecFlow.Tracing.CodeFormattingExtensions.ToIdentifier(String text) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Utils\Steps\CodeFormattingExtensions.cs:line 25
at ReSharperPlugin.SpecflowRiderPlugin.UnitTestExplorers.SpecflowTestExplorer.CompareDescriptionWithShortName(String scenarioText, IUnitTestElement relatedTest) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\UnitTestExplorers\SpecflowTestExplorer.cs:line 87
at ReSharperPlugin.SpecflowRiderPlugin.UnitTestExplorers.SpecflowTestExplorer.<>c__DisplayClass5_0.<ProcessFile>b__0(IUnitTestElement t) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\UnitTestExplorers\SpecflowTestExplorer.cs:line 66
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable1 source, Func2 predicate)
at ReSharperPlugin.SpecflowRiderPlugin.UnitTestExplorers.SpecflowTestExplorer.ProcessFile(IFile psiFile, IUnitTestElementsObserver observer, Func1 interrupted) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\UnitTestExplorers\SpecflowTestExplorer.cs:line 66 at JetBrains.ReSharper.UnitTestFramework.UnitTestFileExplorer.Explore(IPsiSourceFile sourceFile, IDocument document, Func1 interrupt, Action1 addHighlighting) at JetBrains.ReSharper.UnitTestFramework.Highlighting.UnitTestDaemonProcess.Execute(Action1 committer)
```

**Comment by nemesv** [comment]
The plugin has been updated for 2021.2.EAP3 and can be download from here: https://github.com/SpecFlowOSS/SpecFlow.Rider/suites/2973053259/artifacts/67049510
