### ISSUE TITLE
NullReferenceException thrown in GerkinLexer.Advance in Rider 2021.1.5

### ISSUE THREAD

**Issue by Psigio** [SpecFlowOSS/SpecFlow.Rider#150]
When starting Rider, the following error is reported in the idea.log file and the Specflow plugin features do not appear to work (no syntax highlighting, step generation nor navigation from feature files):

```
Message = “Object reference not set to an instance of an object.”
ExceptionPath = Root.InnerException
ClassName = System.NullReferenceException
Data.ThreadLocalDebugInfo = GroupingEventHost.ExecuteExpiredEvents
HResult = E_POINTER=COR_E_NULLREFERENCE=80004003
Source = ReSharperPlugin.SpecflowRiderPlugin
StackTraceString = “
  at ReSharperPlugin.SpecflowRiderPlugin.Psi.GherkinLexer.Advance() in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Psi\GherkinLexer.cs:line 204
     at ReSharperPlugin.SpecflowRiderPlugin.Psi.GherkinLexer.Start() in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\Psi\GherkinLexer.cs:line 50
     at JetBrains.ReSharper.Psi.Parsing.TokenBuffer..ctor(ILexer lexer)
     at JetBrains.ReSharper.Psi.Parsing.LexerExtensions.ToCachingLexer(ILexer lexer)
     at JetBrains.ReSharper.Psi.Files.CachedPsiFile..ctor(IPsiSourceFile sourceFile, PsiLanguageType langType, ReferenceProviderFactory referenceProviderFactory, ILexerFactory lexerFactory, IShellLocks locks)
     at JetBrains.ReSharper.Psi.Files.PsiFilesCommit.BuildPrimary(PreparedSourceFile preparedSourceFile)
     at JetBrains.ReSharper.Psi.Files.PsiFilesCommit.Build(ICollection`1 sourceFilesToCommit, Boolean reparse, IPsiFilesCache psiFilesCache)
```

Unfortunately I am not able to provide a reproduction feature file as I am not sure which file is causing the exception.

I am using Rider 2021.1.5 on Ubuntu 20.04.2 with dotnet core 5.0.302 and version 1.8.0 of the Specflow plugin.  Looking at the GherkinLexer.cs file in the Github repository, it appears that the exception is referring to a `foreach` instruction using the `_myKeywords` collection.

**Comment by nemesv** [comment]
Which language are you using in your feature files? 
If not English is it configured with the #langauge comment or in the specflow.json?

**Comment by nemesv** [comment]
I was able to reproduce this issue, you are using a specflow.json where the language\feature is null or an empty string.
You need to set it to a valid language.
We will fix this default value handling in the next release.

**Comment by Psigio** [comment]
Hi - I just checked the specflow.json and yes, you are correct; it appears that it is an empty string:

```
{
  "language": {
    "feature": ""
  },
  "generator": {
    "allowDebugGeneratedFiles": true,
    "missingOrPendingStepsOutcome": "Error"
  }
}
```
I altered this to:
```
{
  "language": {
    "feature": "en-GB"
  },
  "generator": {
    "allowDebugGeneratedFiles": true,
    "missingOrPendingStepsOutcome": "Error"
  }
}
```
and then executed the "Invalidate Caches & Restart" option in Rider and the plugin is now working.  Many thanks for your quick response, I will close the ticket.
