### ISSUE TITLE
Fatal error occurred during reading project templates due to NullReferenceException

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#155]
Please, see https://youtrack.jetbrains.com/issue/RIDER-67344

ACTUAL:
`or actual registered key = REGEXP.BRACKETS-->DEFAULT_BRACKETS-->null, keys sausage for model fallback key = null

21:53:42.758 | ERROR | Projected Logger               | IdeaLoggingEvent[message=Object reference not set to an instance of an object.

--- EXCEPTION #1/2 [NullReferenceException]

Message = “Object reference not set to an instance of an object.”

ExceptionPath = Root.InnerException

ClassName = System.NullReferenceException

Data.ThreadLocalDebugInfo = “

  property `MainProtocol.ProjectTemplatesModel.session` (12722397014127977585)

   -> DelayedInitializationStrategy.Dispatch: JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.ProjectTemplatesHost [Singleton, Null]

”

HResult = E_POINTER=COR_E_NULLREFERENCE=80004003

Source = ReSharperPlugin.SpecflowRiderPlugin

StackTraceString = “

  at ReSharperPlugin.SpecflowRiderPlugin.ProjectTemplateParameters.TargetFrameworkProviderParameter.CreateContent(DotNetProjectTemplateExpander expander, IDotNetTemplateContentFactory factory, Int32 index, IDictionary`2 context) in D:\a\SpecFlow.Rider\SpecFlow.Rider\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\ProjectTemplateParameters\TargetFrameworkProviderParameter.cs:line 24

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetExtensions.AuthenticationParameterProvider.AuthenticationParameter.CreateContent(DotNetProjectTemplateExpander expander, IDotNetTemplateContentFactory factory, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetExtensions.TargetFrameworkParameter.CreateContent(DotNetProjectTemplateExpander expander, IDotNetTemplateContentFactory factory, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.Xamarin.Templates.AndroidApiParameter.CreateContent(DotNetProjectTemplateExpander expander, IDotNetTemplateContentFactory factory, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetExtensions.DotNetTemplateGroup.CreateContent(IReadOnlyCollection`1 expanders, IDotNetTemplateContentFactory factory, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetExtensions.DotNetTemplateGroup.CreateContent(IReadOnlyCollection`1 expanders, IDotNetTemplateContentFactory factory, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetExtensions.DotNetTemplateGroup.CreateContent(IReadOnlyCollection`1 expanders, IDotNetTemplateContentFactory factory, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetExtensions.DotNetTemplateGroup.CreateContent(IReadOnlyCollection`1 expanders, IDotNetTemplateContentFactory factory, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.CreateNextParameters(IReadOnlyCollection`1 expanders, Int32 index, IDictionary`2 context)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesMatcher.Match(EngineEnvironmentSettings settings, List`1 templateInfoList)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesIntegration.GetTemplateList(SettingsLoader settingsLoader, EngineEnvironmentSettings environmentSettings)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.DotNetTemplates.DotNetTemplatesIntegration.LoadTemplates(IReadOnlyCollection`1 sources, Boolean creatingSolution, Boolean useCachedTemplates)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.ProjectTemplatesHost.<>c__DisplayClass7_0.<.ctor>b__0(Lifetime sessionLifetime, RdProjectTemplateSession session)

”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]

Message = “Object reference not set to an instance of an object.”

ExceptionPath = Root

ClassName = JetBrains.Util.LoggerException

InnerException = “Exception #1 at Root.InnerException”

HResult = COR_E_APPLICATION=80131600

StackTraceString = “

  at JetBrains.Util.ILoggerEx.LogException(ILogger this, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment)

     at JetBrains.Util.ILoggerEx.Error(ILogger this, Exception exception, ExceptionOrigin origin, String comment)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.ProjectTemplatesHost.<>c__DisplayClass7_0.<.ctor>b__0(Lifetime sessionLifetime, RdProjectTemplateSession session)

     at JetBrains.Collections.Viewable.ReactiveEx.<>c__DisplayClass7_0`1.<View>b__0(T v)

     at JetBrains.Collections.Viewable.ViewableProperty`1.Advise(Lifetime lifetime, Action`1 handler)

     at JetBrains.Rd.Impl.RdProperty`1.Advise(Lifetime lifetime, Action`1 handler)

     at JetBrains.Collections.Viewable.ReactiveEx.View[T](IReadonlyProperty`1 me, Lifetime lifetime, Action`2 handler)

     at JetBrains.Rider.Backend.Features.ProjectModel.ProjectTemplates.ProjectTemplatesHost..ctor(Lifetime lifetime, ILogger logger, UITaskExecutor taskExecutor, ProjectTemplatesModel projectTemplatesModel, MsBuildProjectReader projectReader, IProjectTemplatesIntegration integration, IEnumerable`1 autoParameters, UsageStatistics usageStatistics, DotNetTemplateSource dotNetTemplateSource)

     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

     at JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor.CreateInstanceOf(Type type, IValueResolveContext context)

     at JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor.CreateInstance(IValueResolveContext context)

     at JetBrains.Application.Components.SingletonDescriptor.CreateInstanceChecked(OnError onError, IComponentContainer container)

     at JetBrains.Application.Components.SingletonDescriptor.GetValue()

     at JetBrains.Application.Components.DelayedInitializationStrategy.<Dispatch>b__8_1()

     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass1_0.<Run>b__0(Object _)

     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass0_0.<Run>b__0(Object _)

     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, ContextCallback callback, Object state)

     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, Action action)

     at JetBrains.Threading.ReentrancyGuard.QueuedAction.<>c__DisplayClass2_0.<.ctor>b__0()

     at JetBrains.Threading.ReentrancyGuard.Execute(String name, Action action)

     at JetBrains.Threading.ReentrancyGuard.ExecutePendingActions()

     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass1_0.<Run>b__0(Object _)

     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass0_0.<Run>b__0(Object _)

     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, ContextCallback callback, Object state)

     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, Action action)

     at JetBrains.Threading.JetDispatcher.Closure.<>c__DisplayClass10_1.<.ctor>b__0()

     at JetBrains.Threading.JetDispatcher.Closure.Execute()

     at JetBrains.Threading.JetDispatcher.Run()

     at JetBrains.Rider.Backend.Product.RiderMain.Main(Lifetime lifetime, IRiderSettings settings, ILogger logger, ProtocolComponent protocol, RdShellModel shellModel, ApplicationShutdownRequests shutdownRequests)

     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

     at JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_0.<.ctor>b__0()

     at JetBrains.Application.Environment.RunsPublicStaticIntMain.<>c__DisplayClass0_2.<.ctor>b__5()

     at JetBrains.Util.Logging.Logger.Catch(Action action)

     at JetBrains.Application.Threading.IThreadingEx.<>c__DisplayClass18_1.<ExecuteOrQueueWhenNotGuarded>b__4()

     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass1_0.<Run>b__0(Object _)

     at JetBrains.Util.Concurrency.ExecutionContextEx.<>c__DisplayClass0_0.<Run>b__0(Object _)

     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, ContextCallback callback, Object state)

     at JetBrains.Util.Concurrency.ExecutionContextEx.Run(ExecutionContext context, Action action)

     at JetBrains.Threading.JetDispatcher.Closure.<>c__DisplayClass10_1.<.ctor>b__0()

     at JetBrains.Threading.JetDispatcher.Closure.Execute()

     at JetBrains.Threading.JetDispatcher.Run(Func`1 condition, TimeSpan timeout, Boolean bThrowOnTimeout)

     at JetBrains.Application.Environment.IJetHostEx.RunHostMessageLoop(IComponentContainer containerEnv)

     at JetBrains.Application.Environment.HostParameters.MessagePumpMainLoopHostMixin.JetBrains.Application.Environment.HostParameters.IRunMainLoopHostMixin.RunMainLoop(ComponentContainer containerEnv)

     at JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.RunMainLoop(ComponentContainer containerEnv)

     at JetBrains.Application.Environment.JetEnvironment.InternalRun(JetHostParametersCaller host, ComponentContainer containerEnv)

     at JetBrains.Application.Environment.JetEnvironment.CreateAndRun(Full hostparams)

     at JetBrains.Application.Environment.JetHostItems.CreateAndRun(Full input)

     at JetBrains.Rider.Backend.Product.RiderBackendProgram.MainX(Assembly assembly, HostInfo hostInfo, String[] args)

     at JetBrains.Rider.Backend.Product.RiderBackendProgram.<>c.<Main>b__3_0(Lifetime lifetime)

     at JetBrains.Lifetimes.Lifetime.Using[T](Func`2 action)

     at JetBrains.Rider.Backend.Product.RiderBackendProgram.Main()

”

, throwable=com.jetbrains.rdclient.util.BackendException: Object reference not set to an instance of an object.`

**Comment by alimogithub** [comment]
@tkapustina Thanks for raising this, we will look into it.

**Comment by Socolin** [comment]
Should be fixed in 1.14.2
