### ISSUE TITLE
Exception is thrown

### ISSUE THREAD

**Issue by MToolMakerJB** [SpecFlowOSS/SpecFlow.Rider#158]
--- EXCEPTION #1/2 [AssertionException]
Message = “JetBrains.ReSharper.Psi.Tree.IFile is null”
ExceptionPath = Root.InnerException
ClassName = JetBrains.Diagnostics.Assertion+AssertionException
HResult = COR_E_EXCEPTION=80131500
Source = JetBrains.Lifetimes
```stacktrace
StackTraceString = “
  at JetBrains.Diagnostics.Assertion.Fail(String message)
     at ReSharperPlugin.SpecflowRiderPlugin.Caching.StepsUsages.SpecflowStepsUsagesCache.Build(IPsiSourceFile sourceFile, Boolean isStartup) in ReSharperPlugin.SpecflowRiderPlugin\Caching\StepsUsages\SpecflowStepsUsagesCache.cs:line 38
     at JetBrains.ReSharper.Psi.Caches.Jobs.JobUpdateProjectFiles.<>c__DisplayClass15_0.<BuildSourceFile>b__0()
```
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “JetBrains.ReSharper.Psi.Tree.IFile is null”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
```stacktrace
StackTraceString = “
  at JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex)
     at JetBrains.Diagnostics.LogEx.Error(ILog this, Exception ex, String message)
     at JetBrains.Util.Logging.Logger.LogException(Exception ex)
     at JetBrains.ReSharper.Psi.Caches.Jobs.JobUpdateProjectFiles.<>c__DisplayClass15_0.<BuildSourceFile>b__0()
     at JetBrains.Util.Logging.LoggerStructuredEx.DoCalculation[T](Nullable`1 logWithLevel, String key, String message, Func`1 action, Func`2 report)
     at JetBrains.ReSharper.Psi.Caches.Jobs.JobUpdateProjectFiles.BuildSourceFile(IPsiSourceFile sourceFile, IDocument doc)
     at JetBrains.ReSharper.Psi.Caches.Jobs.JobUpdateProjectFiles.<>c__DisplayClass14_1.<ExecuteUpdate>b__1(IPsiSourceFile file, IDocument doc)
     at JetBrains.ReSharper.Psi.Caches.Jobs.CacheJobService2.<>c__DisplayClass38_0`2.<WrappedJob>b__0()
     at JetBrains.ReSharper.Psi.Caches.Jobs.CacheJobService2.<>c__DisplayClass36_0`2.<ExecuteWithPrerocessAndInterrupt>b__1(T x, TPreprocessResult y)
     at JetBrains.Application.Threading.Tasks.TaskHostEx.<>c__DisplayClass5_1`2.<PreprocessSingleThreadedAndParallelize>b__1()
     at JetBrains.Application.Threading.Tasks.TaskHost.AccessViolationCatcher(Action action)
     at JetBrains.Application.Threading.Tasks.TaskHost.<>c__DisplayClass36_0.<Create>b__1(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
     at System.Threading.Tasks.Task.ExecuteEntry()
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask()
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc()
     at JetBrains.Util.Reflection.CallStackAnnotation.CatchAnnotatedInvocation[TClassOfNewFrame](String methodNameOfNewFrame, Action actionToAnnotate)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.<>c__DisplayClass6_0.<.ctor>b__0()
     at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart()
```

`IPsiSourceFile.GetPrimaryPsiFile` can return `null` value so it shouldn't be checked with `.NotNull()` assertion. To check whether you should consider psi file you should use `SimpleICache.IsApplicable`.

**Comment by Socolin** [comment]
It should be fix, can you test this build ? https://github.com/SpecFlowOSS/SpecFlow.Rider/actions/runs/1349638945

**Comment by Socolin** [comment]
I'm closing.

Since there is no response, I asume it's fixed
