### ISSUE TITLE
All Specflow tests failing with "Result collection has not been started"

### ISSUE THREAD

**Issue by tkapustina** [SpecFlowOSS/SpecFlow.Rider#170]
Initial request https://youtrack.jetbrains.com/issue/RIDER-75664

```
System.InvalidOperationException : Result collection has not been started.

   at TechTalk.SpecFlow.CucumberMessages.TestRunResultCollector.CollectTestResultForScenario(ScenarioInfo scenarioInfo, TestResult testResult) in D:\a\1\s\TechTalk.SpecFlow\CucumberMessages\TestRunResultCollector.cs:line 30

   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep() in D:\a\1\s\TechTalk.SpecFlow\Infrastructure\TestExecutionEngine.cs:line 217

   at Workflow.Specs.CoreElements.ConvertFromCamt.ConvertFromCamtToMt940ZV2Feature.ScenarioCleanup()

   at Workflow.Specs.CoreElements.ConvertFromCamt.ConvertFromCamtToMt940ZV2Feature.ConvertAStaticCamt053FileToMt940ZV2FileFormat() in D:\anz\FAW3\VS\Workflow.Specs\CoreElements\ConvertFromCamt\ConvertFromCamtToMt940ZV2.feature:line 16
```

**Comment by SabotageAndi** [comment]
This is an SpecFlow issue. Has nothing to do with the Rider extension.
It is fixed in the latest version, as we have removed this functionality with it.

I will answer also the issue in the JetBrains issue tracker.

**Comment by tkapustina** [comment]
Thank you very much!
