### ISSUE TITLE
Wrong tableId to code in GetCodedTableId. Type HasCustomAttribute, tableId CustomAttribute

### ISSUE THREAD

**Issue by eterekhin** [SpecFlowOSS/SpecFlow.Rider#208]
Could you please take a look at this DEXP?

https://youtrack.jetbrains.com/issue/DEXP-754471/Wrong-tableId-to-code-in-GetCodedTableId.-Type-HasCustomAttribute-tableId-CustomAttribute

**Comment by Socolin** [comment]
@eterekhin Do you have any more information to share, like a stacktrace ?  I cannot see any information on this ticket except the title, is it normal ?

**Comment by eterekhin** [comment]
Hey! Sorry, I've attached the stack trace. Looks like it is [here](https://github.com/SpecFlowOSS/SpecFlow.Rider/blame/master/src/dotnet/ReSharperPlugin.SpecflowRiderPlugin/Caching/StepsDefinitions/ScopeAttributeReader.cs#L79C35-L79C35).
The issue here is that you can't obtain ``CustomAttributes`` from ``IMetadataCustomAttribute``. Empty collection is returned and the ``foreach`` body after the ``if`` seems to be never executed

```  at JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex) in Log.il:line IL_0003 mvid 50B9
     at JetBrains.Diagnostics.LogEx.Error(ILog this, String message)
     at JetBrains.Util.Logging.Logger.LogError(String message) 
     at JetBrains.Util.Logging.Logger.Fail(String messageText)
     at JetBrains.Util.Logging.Logger.Fail(String format, Object[] args)
     at JetBrains.Metadata.Access.ILReader.CodedTokenTables.GetCodedTableId(EncodedTokenType type, MetadataTableId tableId) 
     at JetBrains.Metadata.Access.ILReader.CodedTokenTables.TokenToRawToken(MetadataToken token, MetadataTokenType targetFormat)
     at JetBrains.Metadata.Access.ILReader.ILReaderMetadataAccess.SearchInTable(MetadataTableId table, MetadataToken targetToken, MetadataTokenType targetStorageFormat, Int32 skipBytes, MetadataTokenType[] skipTokenTypes)
     at JetBrains.Metadata.Access.ILReader.MetadataAccessBase.GetCustomAttributes(MetadataToken parentToken) in GetCustomAttributes.il:line IL_0000 mvid 7C07
     at JetBrains.Metadata.EditAndContinue.EncMetadataAccessEx.GetCustomAttributesTypeNames(IMetadataAssembly metadataAssembly, MetadataToken ownerToken)
     at JetBrains.Metadata.Reader.Impl.MetadataEntity.get_CustomAttributesTypeNames()
     at ReSharperPlugin.SpecflowRiderPlugin.Caching.StepsDefinitions.ScopeAttributeUtil.GetScopesFromAttributes(ICollection`1 attributeInstances)
     at ReSharperPlugin.SpecflowRiderPlugin.Caching.StepsDefinitions.AssemblyStepDefinitions.AssemblyStepDefinitionCache.<>c__DisplayClass11_0.<Build>b__0(IPsiAssembly _, IPsiAssemblyFile _, IMetadataAssembly metadataAssembly)
     at JetBrains.ReSharper.Psi.Impl.reflection2.AssemblyFileLoaderZoned.PsiAssemblyFileLoader.InvokeProcessorAndReturn(IPsiAssemblyFile assemblyFile, IPsiAssembly psiAssembly, Action`3 processor) in InvokeProcessorAndReturn.il:line IL_003C mvid DFDF
     at JetBrains.ReSharper.Psi.Impl.reflection2.AssemblyFileLoaderZoned.PsiAssemblyFileLoader.GetOrLoadAssembly(IPsiAssembly psiAssembly, Boolean shouldLoad, Action`3 processor)
     at ReSharperPlugin.SpecflowRiderPlugin.Caching.StepsDefinitions.AssemblyStepDefinitions.AssemblyStepDefinitionCache.Build(IPsiAssembly assembly)
```

**Comment by Socolin** [comment]
Should be fix with the next version
