### ISSUE TITLE
Initialization of [ReSharperPlugin.SpecflowRiderPlugin.Navigation.SpecflowStepOccurenceInfoProvider, ReSharperPlugin.SpecflowRiderPlugin, Version=1.23.6.0, Culture=neutral, PublicKeyToken=null] failed, [JetBrains.ReSharper.Psi.SolutionFeaturePartAttribute, JetBrains.ReSharper.Psi, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325] ctor need explicit instantiation parameter

### ISSUE THREAD

**Issue by van800** [SpecFlowOSS/SpecFlow.Rider#215]
Submitted in https://youtrack.jetbrains.com/issue/DEXP-778924/Data-Redacted

Summary: Data Redacted

Description:
JetBrains Rider 2024.1 Build RD-241.13688.41 Date 2024-02-26T11:44:00.000+0000

Initialization of [ReSharper.Structured.Logging.Caching.TemplateParameterNameAttributeProvider, ReSharper.Structured.Logging.Rider, Version=2024.1.0.323, Culture=neutral, PublicKeyToken=null] failed, [JetBrains.ReSharper.Psi.CodeAnnotations.CodeAnnotationProviderAttribute, JetBrains.ReSharper.Psi, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325] ctor need explicit instantiation parameter

--- EXCEPTION #1/1 [LoggerException]
Message = â€œInitialization of [ReSharper.Structured.Logging.Caching.TemplateParameterNameAttributeProvider, ReSharper.Structured.Logging.Rider, Version=2024.1.0.323, Culture=neutral, PublicKeyToken=null] failed, [JetBrains.ReSharper.Psi.CodeAnnotations.CodeAnnotationProviderAttribute, JetBrains.ReSharper.Psi, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325] ctor need explicit instantiation parameterâ€
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
StackTraceString = â€œ
  at JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex) in Log.il:line IL_0003 mvid 6768
     at JetBrains.Diagnostics.LogEx.Error(ILog this, String message) in Error.il:line IL_0000 mvid D6DC
     at JetBrains.Util.Logging.Logger.LogError(String message) in LogError.il:line IL_0000 mvid 6768
     at JetBrains.Util.Logging.Logger.Fail(String messageText) in Fail.il:line IL_001A mvid 6768
     at JetBrains.Application.Parts.ComponentProperties.Read(PartCatalogType sourceType, PartCatalogAttribute pca, Instantiation instantiation) in Read.il:line IL_0000 mvid DEF0
     at JetBrains.Application.Parts.ComponentProperties.FromAttribute(PartCatalogType sourceType, PartCatalogAttribute pca, Instantiation defaultInstantiation) in FromAttribute.il:line IL_0021 mvid DEF0
     at JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor.GetComponentProperties(PartCatalogType part, Type typeAttrBase, Instantiation defaultInstantiation) in GetComponentProperties.il:line IL_001B mvid DEF0
     at JetBrains.Application.Extensibility.ComponentDescriptorFactory.GetPartCatalogTypeDescriptors(PartCatalogType part)+MoveNext()
     at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection) in AddRange.il:line IL_0083 mvid 477B
     at JetBrains.Application.Extensibility.CatalogComponentSource.GetDescriptors(IComponentContainer container, IPartCatalogSet catalogset, IPartSelector selector, IEnumerable`1 filters, Type catalogAttributeType) in GetDescriptors.il:line IL_0091 mvid DEF0
     at JetBrains.Application.Components.NestedComponentContainerValueResolver.NestedComponentContainerValueDescriptorBase`2..ctor(IValueResolveContext originalResolveContext, TRegisterStrategy strategy, IComponentContainer originalComponentContainer)
     at JetBrains.Application.Components.NestedComponentContainerValueResolver.NestedComponentContainerValueDescriptorHelper`2..ctor(IValueResolveContext context, IComponentContainer componentContainer)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) in InvokeDirectByRefWithFewArgs.il:line IL_007E mvid 477B
     at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in InvokeWithFewArgs.il:line IL_00A7 mvid 477B
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in Invoke.il:line IL_006A mvid 477B
     at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) in CreateInstanceImpl.il:line IL_017C mvid 477B
     at JetBrains.Application.Components.NestedComponentContainerValueResolver.Resolve[TRequest](ResolveRequest`1 request, ValueResolveFlags flags, IValueResolveContext context) in Resolve.il:line IL_0055 mvid DEF0
     at JetBrains.Application.Components.ComponentContainer.ResolveCore[TRequest](ResolveRequest`1 request, ValueResolveFlags flags, IValueResolveContext context) in ResolveCore.il:line IL_009A mvid DEF0
     at JetBrains.Application.Components.ComponentContainer.Resolve[TRequest](ResolveRequest`1 request, ValueResolveFlags flags, IValueResolveContext context) in Resolve.il:line IL_0000 mvid DEF0
     at JetBrains.Application.Components.ComponentResolveContext.Resolve[TRequest](ResolveRequest`1 request, ValueResolveFlags flags) in Resolve.il:line IL_000C mvid DEF0
     at JetBrains.Application.Components.ValueResolveContextEx.Resolve(IValueResolveContext context, Type request, ValueResolveFlags flags) in Resolve.il:line IL_0000 mvid DEF0
     at JetBrains.Application.Components.SignatureResolution.BindToMethod(MethodBase[] candidates, IValueResolveContext context, Object origin) in BindToMethod.il:line IL_0046 mvid DEF0
     at JetBrains.Application.Extensibility.PartCatalogTypeComponentDescriptor.DoGetDependenciesNoCache() in DoGetDependenciesNoCache.il:line IL_0025 mvid DEF0
     at JetBrains.Application.Components.SingletonDescriptor`1.DoGetDependenciesNoCacheValidated() in DoGetDependenciesNoCacheValidated.il:line IL_0000 mvid DEF0
     at JetBrains.Application.Components.SingletonDescriptor`1.TryGetCachedDependencies(Boolean allowGetValueIfNotAlive) in TryGetCachedDependencies.il:line IL_0062 mvid DEF0
     at JetBrains.Application.Components.SingletonDescriptor`1.DoGetDependencies() in DoGetDependencies.il:line IL_0000 mvid DEF0
     at JetBrains.Application.Components.AsyncDescriptorBase.GetDependencies() in GetDependencies.il:line IL_001A mvid DEF0
     at JetBrains.Application.Components.ComponentStorage.WarmUpDescriptors(Lifetime lifetime, ICollection`1 descriptors, String containerId) in WarmUpDescriptors.il:line IL_0056 mvid DEF0
     at JetBrains.Application.Components.ComponentStorage.<>c__DisplayClass25_0.<InstantiateDescriptors>b__0() in ComponentStorage.il:line IL_0000 mvid DEF0
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 477B
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in ExecuteWithThreadLocal.il:line IL_0096 mvid 477B
     at System.Threading.Tasks.Task.ExecuteEntry() in ExecuteEntry.il:line IL_0036 mvid 477B
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task) in ExecuteTask.il:line IL_0014 mvid 6768
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask() in EnqueueNextTask.il:line IL_0009 mvid 6768
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc() in ThreadPoolProc.il:line IL_0197 mvid 6768
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.StartProc() in StartProc.il:line IL_0000 mvid 6768
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 477B
â€

last.action = Git.Log.Branches.Change.Branch.Filter

app.eap = true
app.internal = false
app.build = RD-241.13688.41
app.version.major = 2024
app.version.minor = 1
app.build.date = 2024-02-26T11:44:00.000+0000
app.build.date.release = 2024-02-26T11:44:00.000+0000
app.build.date.release = 2024-02-26T11:44:00.000+0000
app.product.code = RD

os.name = Windows
os.cpu.arch = amd64
java.version = 17.0.10
java.vm.vendor = JetBrains s.r.o.

UIUtil.isRetina = false
JBUI.isHiDPI() = false
ImageScaleFactor = 1

netcore = true

.NET Core v8.0.1 x64 (Server GC)

**Comment by Socolin** [comment]
The plugin is not compatible with 2024.1 and I cannot push new updates. I'll push a new version for the forked version of specflow when I get some time. There is already a build available on github action

**Comment by van800** [comment]
@Socolin Rider 2024.1 is close to release, so if I may ask, please publish a compatible plugin update.
