### ISSUE TITLE
Error when "space" or "tab" is pressed in the feature file

### ISSUE THREAD

**Issue by alexandrafung** [SpecFlowOSS/SpecFlow.Rider#50]
![error](https://user-images.githubusercontent.com/8384757/111490448-52fc0380-873b-11eb-95e4-c2d3a118e1ab.gif)

**Stack trace:**

com.jetbrains.rdclient.util.BackendException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. insertRange.StartOffset == replaceRange.StartOffset

--- EXCEPTION #1/3 [AssertionException]
Message = “insertRange.StartOffset == replaceRange.StartOffset”
ExceptionPath = Root.InnerException.InnerException
ClassName = JetBrains.Diagnostics.Assertion+AssertionException
HResult = COR_E_EXCEPTION=80131500
Source = JetBrains.Lifetimes
StackTraceString = “
  at JetBrains.Diagnostics.Assertion.Fail(String message)
     at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.TextLookupRanges..ctor(DocumentRange insertRange, DocumentRange replaceRange, PrefixTextRule customPrefixRule)
     at ReSharperPlugin.SpecflowRiderPlugin.CompletionProviders.GherkinCompletionContextProvider.GetCompletionContext(CodeCompletionContext context) in C:\Users\alefu\Work\resharper-specflow\src\dotnet\ReSharperPlugin.SpecflowRiderPlugin\CompletionProviders\GherkinCompletionContextProvider.cs:line 37
     at JetBrains.ReSharper.Feature.Services.CodeCompletion.IntellisenseManager.SpecificCodeCompletionContexts(CodeCompletionParameters parameters, ITextControl textControl)
     at JetBrains.ReSharper.Feature.Services.CodeCompletion.IntellisenseManager.GetCompletionResult(CodeCompletionParameters parameters, ITextControl textControl)
     at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.LookupItemUtil.EmulateFullCompletionResult(ITextControl textControl, IntellisenseManager intellisenseManager, CodeCompletionParameters parameters, EvaluationMode evaluationMode, LookupListSorting lookupListSorting, ICodeCompletionResult previousResult, ItemsByLocation`1 itemsByLocation, Boolean joinWithPreviousResult)
     at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.GetCodeCompletionResult(IntellisenseManager intellisenseManager, ITextControl textControl, CodeCompletionParameters codeCompletionParameters, EvaluationMode evaluationMode, ICodeCompletionResult& completionResult)
     at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<>c__DisplayClass26_0.<CalculateItems>b__0()
     at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.<>c__DisplayClass39_0.<RunAsyncCompletion>b__1()
     at JetBrains.Application.Threading.InterruptableReadActivity.DoWork()
     at JetBrains.Application.Threading.InterruptableReadActivity.WorkerThreadProc()
     at JetBrains.Application.Threading.Tasks.TaskHost.AccessViolationCatcher(Action action)
     at JetBrains.Application.Threading.Tasks.TaskHost.<>c__DisplayClass36_0.<Create>b__1(Object state)
     at System.Threading.Tasks.Task.Execute()
”

**Comment by Socolin** [comment]
I reworked that part, it should be fixed.

**Comment by nemesv** [comment]
Fixed in version 1.4.0
